name: Arduino LCD Compile

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Install Board and Library
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install "LiquidCrystal I2C"

      - name: Compile for Uno
        run: |
          # Creates the 'build' directory and compiles the sketch
          arduino-cli compile --fqbn arduino:avr:uno --output-dir ./build ./lcd_test

      - name: Upload Hex Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arduino-uno-hex
          path: ./build/*.hex
