name: Build LCD Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          # Installs both potential versions of the I2C library
          arduino-cli lib install "LiquidCrystal I2C"
          
          # This compiles ONLY the LCD folder
          arduino-cli compile --fqbn esp32:esp32:esp32 LCD_Display/LCD_Display.ino --export-binaries
          
          python3 -m pip install esptool
          python3 -m esptool --chip esp32 merge_bin \
            -o LCD_Display/lcd_merged.bin \
            --flash_mode dio \
            --flash_size 4MB \
            0x1000 LCD_Display/build/esp32.esp32.esp32/LCD_Display.ino.bootloader.bin \
            0x8000 LCD_Display/build/esp32.esp32.esp32/LCD_Display.ino.partitions.bin \
            0x10000 LCD_Display/build/esp32.esp32.esp32/LCD_Display.ino.bin

      - uses: actions/upload-artifact@v4
        with:
          name: LCD_Firmware
          path: LCD_Display/lcd_merged.bin
