name: Build IR Game
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli lib install "LiquidCrystal I2C"
          arduino-cli lib install "IRremote"
          arduino-cli compile --fqbn esp32:esp32:esp32 IR_Game/IR_Game.ino --export-binaries
          python3 -m pip install esptool
          python3 -m esptool --chip esp32 merge_bin -o IR_Game/game_merged.bin --flash_mode dio --flash_size 4MB 0x1000 IR_Game/build/esp32.esp32.esp32/IR_Game.ino.bootloader.bin 0x8000 IR_Game/build/esp32.esp32.esp32/IR_Game.ino.partitions.bin 0x10000 IR_Game/build/esp32.esp32.esp32/IR_Game.ino.bin
      - uses: actions/upload-artifact@v4
        with:
          name: Game_Firmware
          path: IR_Game/game_merged.bin
