name: Build mc_projects

on:
  push:
    paths:
      - 'mc_projects/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - name: Install ESP32
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
      - name: Install Servo Library
        run: arduino-cli lib install "ESP32Servo"
      - name: Compile
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 mc_projects/ --output-dir build/
      - name: Merge bin files
        run: |
          pip install esptool
          ls build/
          esptool --chip esp32 merge-bin \
            -o build/merged.bin \
            --flash-mode dio \
            --flash-freq 40m \
            --flash-size 4MB \
            0x1000 $(ls build/*.bootloader.bin) \
            0x8000 $(ls build/*.partitions.bin) \
            0x10000 $(ls build/*.ino.bin)
      - name: Upload merged bin
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/merged.bin
