name: Servo Debug Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python and Esptool
        run: pip install esptool

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 Core and Libraries
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install "ESP32Servo"
          arduino-cli lib install "LiquidCrystal I2C"

      - name: Compile
        run: |
          mkdir -p build_output
          arduino-cli compile --fqbn esp32:esp32:esp32 mc_projects/Servo_Rotation/Servo_Rotation.ino --output-dir ./build_output

      - name: Merge Binaries into Single File
        run: |
          esptool.py --chip esp32 merge_bin \
            -o build_output/servo_debug_merged.bin \
            --flash_mode dio \
            --flash_size 4MB \
            0x1000 build_output/Servo_Rotation.ino.bootloader.bin \
            0x8000 build_output/Servo_Rotation.ino.partitions.bin \
            0x10000 build_output/Servo_Rotation.ino.bin

      - name: Upload Zipped Merged Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Servo_Debug_Project
          path: build_output/servo_debug_merged.bin
