name: Servo Only Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - name: Install ESP32 and Servo Lib
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install "ESP32Servo"
      - name: Compile
        run: |
          mkdir out
          arduino-cli compile --fqbn esp32:esp32:esp32 mc_projects/Servo_Rotation/Servo_Rotation.ino --output-dir ./out
      - uses: actions/upload-artifact@v4
        with:
          name: Servo_Bin
          path: out/*.bin
